### ISSUE TITLE
pronunciation guide requires linked audio file

### ISSUE THREAD

**Issue by davidwhogg** [megbedell/wobble#1]
Wahb-lay

**Comment by dfm** [comment]
@davidwhogg: don't you have other work to be doing...

**Comment by davidwhogg** [comment]
Like sanding a table top?

**Comment by megbedell** [comment]
on second thought, I think we need a seasoned thespian like @RuthAngus to record a custom pronunciation guide, because text to speech isn't quite cutting it!

**Comment by megbedell** [comment]
beautiful!
