### ISSUE TITLE
tradeoff between star & telluric models

### ISSUE THREAD

**Issue by megbedell** [megbedell/wobble#11]
Examples shown here. Seems to happen most severely in regions with very strong tellurics (like this band head around 6870 A), but there are a couple of places where this happens in strong stellar absorption lines (like the one at 5600 A).
![model_order71_epoch0](https://user-images.githubusercontent.com/13722237/33578081-47ebb6b8-d913-11e7-8631-657f045520f6.png)
![model_order51_epoch0](https://user-images.githubusercontent.com/13722237/33578090-51fe465c-d913-11e7-98cc-78db2eb6229f.png)

**Comment by davidwhogg** [comment]
I think I know how to fix this -- I have a hack to propose, and a principled method.

**Comment by megbedell** [comment]
I think the regularization has solved this
