### ISSUE TITLE
standardize optimization

### ISSUE THREAD

**Issue by megbedell** [megbedell/wobble#13]
I get different outputs from star.optimize() and star.combine_rvs() when running on my laptop and desktop, using the same exact code and input data on both! I guess this may be related to the scipy.optimize.minimize steps- I'm running scipy version [0.17.0](https://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.optimize.minimize.html) on my laptop and [1.0.0](https://docs.scipy.org/doc/scipy-1.0.0/reference/generated/scipy.optimize.minimize.html) on my desktop. I don't see anything obvious in the documentation but maybe something has changed in the BFGS code between versions?

In any case, since we have derivatives perhaps we should write our own optimizers???

**Comment by davidwhogg** [comment]
The issues might be convergence criteria. We should explicitly set gtol rtol ftol etc so that they are all explicitly identical across platforms.

**Comment by megbedell** [comment]
gtol and eps are already explicitly set, and I think those are the only ones that matter for BFGS.

**Comment by davidwhogg** [comment]
Maxfev?

**Comment by davidwhogg** [comment]
Or, what is the message at each location? Identical?

**Comment by megbedell** [comment]
using TF optimizers
