### ISSUE TITLE
velocity sign issues

### ISSUE THREAD

**Issue by davidwhogg** [megbedell/wobble#2]
We need to audit all code for velocity sign issues. The convention SHOULD be that a positive velocity for the star is a red-shift.

**Comment by megbedell** [comment]
Just leaving some notes for my reference here...
The HARPS CCF file headers give us barycentric correction velocities (BERVs) and barycentric-corrected stellar RVs in km/s. On the other hand, wobble is trying to fit for a "measured RV" that is the actual apparent Doppler shift of the star as viewed from the Earth. After some testing, I _think_ the correct relationship between the two is:
```
RV(star) = RV(measured) + BERV
```
That is, BERV is not the observatory's velocity with respect to the solar system rest frame as earlier versions of wobble assumed, but the negative of that... I think.

That means that the correct initialization of the wobble RVs is -BERVs, not +BERVs. Also, to get the stellar RVs from the wobble measurements, we have to _add_ BERVs to the measured RVs.
