### ISSUE TITLE
figures for paper

### ISSUE THREAD

**Issue by megbedell** [megbedell/wobble#22]
Here's a tentative list of figures that we need to make:

- [ ] data at some epoch, shifted star model, composite tellurics model (for 51 Peg)
- [ ] phase-folded RV curve (for 51 Peg)
- [ ] data at some epoch, shifted star model, composite tellurics model (for quiet M)
- [ ] RV vs time (for quiet M)
- [ ] comparison of tellurics model + B star observation data
- [ ] two-panel plot with (a) chief components of tellurics template plotted and (b) weights vs time for those components

**Comment by davidwhogg** [comment]
We might also plot our RV values and our tellurics weights vs housekeeping data, to show that we are not (obviously) measuring anything Other than RV.

**Comment by megbedell** [comment]
I think we've got all the plots we want now
