### ISSUE TITLE
there are two likelihood functions with repeated code

### ISSUE THREAD

**Issue by davidwhogg** [megbedell/wobble#3]
hogg say: make a `self.lnlike_parts()` that contains all the repeated code

**Comment by megbedell** [comment]
fixed some of this, but there's still edits to be made in the "improve model" and d(lnlike)/dw functions to eliminate duplicate code

**Comment by megbedell** [comment]
Fixed the model and d(lnlike)/dw functions to have less duplication. There's still a bit more duplication that could be eliminated by getting clever with the state function, but I'm calling this done for now at least!
