### ISSUE TITLE
needs documentation

### ISSUE THREAD

**Issue by megbedell** [megbedell/wobble#32]
the docstrings are mostly there so we can run sphinx. at the very least we need an informative README!

**Comment by davidwhogg** [comment]
Yes, and (perhaps as another issue) we need a hello-world few-line example, with data.

**Comment by megbedell** [comment]
I got sphinx running and set wobble up with ReadTheDocs: [https://wobble.readthedocs.io/en/latest/](https://wobble.readthedocs.io/en/latest/)

However, the autodocs don't seem to be working with RTD, although they do work when I build locally on my laptop. Maybe @rodluger or @dfm can help me debug?

Either way, still to do are:
- [x] make README.md more informative
- [x] few-line example

**Comment by megbedell** [comment]
ok the docs aren't perfect but there's something there! I'm calling it done for now, will revisit if & when we make an actual public-facing tool.
