### ISSUE TITLE
likelihood functions return negative ln like

### ISSUE THREAD

**Issue by davidwhogg** [megbedell/wobble#4]
this is a notational issue

**Comment by benmontet** [comment]
I have addressed this in the code as it existed in the last push, but the next time you push @megbedell you need to verify that your updated functions are -lnlike suitable. I think there will be a merge issue with the lnprior terms in the likelihood that you updated this morning so I am going to leave this open for now

**Comment by benmontet** [comment]
Done!

**Comment by benmontet** [comment]
Undone to fix some merge issues

**Comment by benmontet** [comment]
Now fixed
