### ISSUE TITLE
needs requirements list

### ISSUE THREAD

**Issue by megbedell** [megbedell/wobble#55]
Some users have c++ compiling issues (for the interp op) when attempting to install. We should figure out what the requirements are and make them explicit. @dfm @rodluger help??

**Comment by dfm** [comment]
From the C++ side, the only thing that is required is tensorflow.

**Comment by megbedell** [comment]
ok - more details on the C++ issues in #57

**Comment by bjfultn** [comment]
Yeah, I found this to be a macOS Mojave issue rather than a Cython issue as I originally suspected. Still a requirements file is needed. Starting with `tensorflow`

**Comment by dfm** [comment]
Good call!

Yeah - there's no Cython in the house here :-)

Our method for building TensorFlow extensions is a bit of a hack but it's much more sustainable (for us) than the method recommended by TensorFlow crew.
