### ISSUE TITLE
change star class initialization?

### ISSUE THREAD

**Issue by megbedell** [megbedell/wobble#7]
Currently a "star" object needs to contain spectral data upon initialization. It might be worth making a separate star.load_data() function so that it is possible to initialize the object and populate it with star.load_results() without investing the time to load up unnecessary data. Also worth keeping in mind that we may eventually want to have 2+ star objects which share the same tellurics model, which will change the design...

**Comment by davidwhogg** [comment]
We might want a "catalog" object that contains (possibly) multiple "star" instances and a "telluric" instance or something like that.
