### ISSUE TITLE
implement Chromatic RV Index

### ISSUE THREAD

**Issue by megbedell** [megbedell/wobble#75]
[Zechmeister et al](https://arxiv.org/pdf/1710.10114.pdf) introduce a chromatic RV index (CRX) in their SERVAL paper which seems to work well as an activity tracer (see Section 3.1 in linked paper). The index is determined by fitting a line to the RVs reported for each order as a function of the order's mean wavelength. We could do this calculation too!

**Comment by benmontet** [comment]
Ohhh, I have an undergrad who is exploring this idea exactly with wobble this term! He’s using K2-100 as a test case. He’s doing this for course credit so needs to have results by the end of this term and we’d be happy to submit a PR once he’s cooking!

**Comment by megbedell** [comment]
done by @michaelferraro in PR #76 😄
